# Generated by Django 5.2.4 on 2025-07-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "image_1_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "image_2_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "image_3_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("copy_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "generated_post",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("category", models.CharField(max_length=20)),
                ("source_category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_collected", models.BooleanField(default=False)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "keyword",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("social_id", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("naver", "Naver"),
                            ("kakao", "Kakao"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=1000)),
                ("order", models.SmallIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.generatedpost",
                    ),
                ),
            ],
            options={
                "db_table": "image",
            },
        ),
        migrations.AddField(
            model_name="generatedpost",
            name="keyword",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="apps.keyword"
            ),
        ),
        migrations.CreateModel(
            name="ClovaStudioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "성공"), ("fail", "실패")], max_length=20
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.keyword"
                    ),
                ),
            ],
            options={
                "db_table": "clova_studio_log",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("origin_link", models.CharField(max_length=1000)),
                (
                    "keyword",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.keyword"
                    ),
                ),
            ],
            options={
                "db_table": "article",
            },
        ),
        migrations.CreateModel(
            name="KeywordClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.keyword"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.user"
                    ),
                ),
            ],
            options={
                "db_table": "keyword_click_log",
            },
        ),
        migrations.AddField(
            model_name="generatedpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apps.user"
            ),
        ),
        migrations.CreateModel(
            name="CopyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.generatedpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.user"
                    ),
                ),
            ],
            options={
                "db_table": "copy_log",
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.BigIntegerField()),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.user"
                    ),
                ),
            ],
            options={
                "db_table": "admin_log",
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("연예", "Entertainment"),
                            ("경제", "Economy"),
                            ("스포츠", "Sports"),
                            ("패션", "Fashion"),
                            ("자동차", "Car"),
                            ("여행", "Travel"),
                            ("맛집", "Food"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_interest",
                "unique_together": {("user", "category")},
            },
        ),
    ]
