# Generated by Django 5.2.4 on 2025-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
