# Generated by Django 5.2.4 on 2025-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminlog",
            options={
                "verbose_name": "관리자 로그",
                "verbose_name_plural": "관리자 로그 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "기사", "verbose_name_plural": "기사 목록"},
        ),
        migrations.AlterModelOptions(
            name="clovastudiolog",
            options={
                "verbose_name": "Clova 처리 기록",
                "verbose_name_plural": "Clova 처리 기록 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="copylog",
            options={
                "verbose_name": "복사 기록",
                "verbose_name_plural": "복사 기록 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="generatedpost",
            options={
                "verbose_name": "생성된 글",
                "verbose_name_plural": "생성된 글 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "이미지", "verbose_name_plural": "이미지 목록"},
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={"verbose_name": "키워드", "verbose_name_plural": "키워드 목록"},
        ),
        migrations.AlterModelOptions(
            name="keywordclicklog",
            options={
                "verbose_name": "키워드 클릭 기록",
                "verbose_name_plural": "키워드 클릭 기록 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자 목록"},
        ),
        migrations.AlterModelOptions(
            name="userinterest",
            options={
                "verbose_name": "사용자 관심사",
                "verbose_name_plural": "사용자 관심사 목록",
            },
        ),
        migrations.AlterField(
            model_name="keyword",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="keyword",
            unique_together={("title", "category")},
        ),
    ]
