# Generated by Django 5.2.4 on 2025-07-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_adminlog_options_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="keyword",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.keyword",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apps.generatedpost",
            ),
        ),
    ]
