# Generated by Django 5.2.4 on 2025-08-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_image_keyword_alter_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedpost",
            name="keyword",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="apps.keyword"),
        ),
        migrations.AddConstraint(
            model_name="generatedpost",
            constraint=models.UniqueConstraint(fields=("user", "keyword"), name="unique_post_per_user_keyword"),
        ),
    ]
