# Generated by Django 5.2.4 on 2025-08-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_alter_generatedpost_keyword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="keyword",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="apps.keyword",
            ),
        ),
    ]
