# Generated by Django 5.2.4 on 2025-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_alter_article_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpost",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
