# Generated by Django 5.2.4 on 2025-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_generatedpost_is_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="category",
            field=models.CharField(
                choices=[
                    ("연예", "Entertainment"),
                    ("경제", "Economy"),
                    ("스포츠", "Sports"),
                    ("야구", "Baseball"),
                    ("드라마", "Drama"),
                    ("패션", "Fashion"),
                    ("자동차", "Car"),
                    ("여행", "Travel"),
                    ("맛집", "Food"),
                ],
                max_length=20,
            ),
        ),
    ]
